server {
    listen 3000;

    include /etc/nginx/mime.types;

    location ~* \.pdf$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
        add_header Access-Control-Allow-Origin "*" always;
        add_header Content-Disposition "inline" always;
        try_files $uri =404;
    }


    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }

    include /etc/nginx/extra-conf.d/*.conf;
}